### ISSUE TITLE
Unable to delete note

### ISSUE THREAD

**Issue by Petros0** [coollabsio/note.coollabs.io#16]
Chrome Version: 75.0.3770.142 (Official Build) (64-bit)
OS: Windows 10

Hi,

I was trying to delete a note but it didn't work. After taking a look in the console I got that error:

 
> Access to XMLHttpRequest at 'https://wss.coollabs.io/coolsocket/EIO=3&transport=polling&t=Mm4WMW7' from origin 'https://note.coollabs.io' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

![image](https://user-images.githubusercontent.com/12134197/61448504-49613d80-a953-11e9-82ab-2580db443b47.png)

After refresh, it's still there.

![image](https://user-images.githubusercontent.com/12134197/61448531-55e59600-a953-11e9-8fa1-aaa766016f0d.png)

Devtools:
![image](https://user-images.githubusercontent.com/12134197/61448558-6433b200-a953-11e9-81ae-233e82132411.png)

**Comment by andrasbacsai** [comment]
We do not use wildcard CORS headers on our side.

Do you use any browser extensions which overwrites the CORS header, like [this](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) one?

**Comment by Petros0** [comment]
Hi @andrasbacsai,

You are right. I was using a plugin. Sorry, my fault.

Thank you!
